---
variables:
  PYTHON_IMAGE_TAG: 3.9.7
stages:
  - build
  - deploy

build_package:
  stage: build
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:$PYTHON_IMAGE_TAG
  artifacts:
    paths:
      - dist
  script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
    - export PATH=$HOME/.local/bin:$PATH
    - poetry build

deploy_package:
  stage: deploy
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/python:$PYTHON_IMAGE_TAG
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'
  script:
    - curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
    - export PATH=$HOME/.local/bin:$PATH
    - poetry config repositories.privatepypi ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry publish --repository privatepypi --username gitlab-ci-token --password ${CI_JOB_TOKEN}
